services:
  member-service:
    volumes:
      - /memberService:/usr/src/app
    container_name: memberservice
    build:
      context: /memberService
    depends_on:
      - mydb
    ports:
      - 8081:8080
    networks:
      - ysg
  auth-service:
    volumes:
      - /authService:/usr/src/app
    container_name: authservice
    build:
      context: /authService
    depends_on:
      - mydb
    ports:
      - 8082:8080
    networks:
      - ysg
  mydb:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 1149
    volumes:
      - database:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - ysg

volumes:
  database:

networks:
  ysg:

x-environment:
  project_name: myproject